---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: redis-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: redis-operator
      version: '0.15.9'
      sourceRef:
        kind: HelmRepository
        name: redis-operator
        namespace: flux-system
      interval: 1m
  values:
    redisOperator:
      imageTag: v0.15.0-arm64
