---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synapse
spec:
  install:
    remediation:
      retries: -1
  upgrade:
    remediation:
      retries: -1
  interval: 5m
  timeout: 20m
  chart:
    spec:
      chart: matrix-synapse
      version: '3.9.12'
      sourceRef:
        kind: HelmRepository
        name: ananace
        namespace: flux-system
  values:
    serverName: siewert.io
    publicServerName: matrix.frickel.earth
    persistence:
      enabled: true
      storageClass: hcloud-volumes
      size: 10Gi
    signingkey:
      job:
        enabled: false
    config:
      enableRegistration: false
    synapse:
      strategy:
        type: Recreate
      extraVolumes:
        - name: smtp-config
          secret:
            secretName: synapse-smtp-config
      extraVolumeMounts:
        - name: smtp-config
          mountPath: /synapse/config/conf.d/smtp.yaml
          subPath: smtp_config
          readOnly: true
    workers:
      default:
        annotations:
          prometheus.io/scrape: 'true'
          prometheus.io/port: '9090'
          prometheus.io/path: /_synapse/metrics
      pusher:
        enabled: true
      frontend_proxy:
        enabled: true
        csPaths:
          - "/_matrix/client/(api/v1|r0|v3|unstable)/keys/upload"
          - "/_matrix/client/(api/v1|r0|v3|unstable)/presence/[^/]+/status"
    extraConfig:
      use_presence: true
    ingress:
      traefikPaths: true
    postgresql:
      enabled: false
    externalPostgresql:
      host: general-db1-prod.postgres
      username: synapse
      database: synapse

      existingSecret: synapse.general-db1-prod.credentials.postgresql.acid.zalan.do
      existingSecretPasswordKey: password
