---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgres-operator
spec:
  interval: 5m
  chart:
    spec:
      chart: postgres-operator
      version: '1.12.0'
      sourceRef:
        kind: HelmRepository
        name: zalando-postgres-operator
        namespace: flux-system
      interval: 1m
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    image:
      registry: ghcr.io
      repository: zalando/postgres-operator
    configKubernetes:
      enable_cross_namespace_secret: true
