---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
spec:
  interval: 30m
  chart:
    spec:
      chart: reflector
      version: '7.1.256'
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
      interval: 10m
