---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: promtail
spec:
  interval: 5m
  timeout: 20m
  chart:
    spec:
      version: "6.16.6"
      chart: promtail
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 60m
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: promtail-values
      valuesKey: promtail.values.yaml
