---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: traefik
      version: '26.1.0'
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 1m
  values:
    deployment:
      kind: DaemonSet
    service:
      annotations:
        load-balancer.hetzner.cloud/location: fsn1
        load-balancer.hetzner.cloud/uses-proxyprotocol: "true"
    ports:
      websecure:
        proxyProtocol:
          trustedIPs:
            - 2a01:4f8:c011:8a4::1
            - 49.12.17.140
