---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager-webhook-hetzner
  namespace: flux-system
spec:
  interval: 1h
  url: https://vadimkim.github.io/cert-manager-webhook-hetzner
