apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: traefik
      version: '26.1.0'
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 1m
  values:
    deployment:
      kind: DaemonSet
    service:
      externalTrafficPolicy: Local
      ipFamilyPolicy: "RequireDualStack"
      ipFamilies:
      - IPv4
      - IPv6
