apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: cilium
      version: '1.15.5'
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
      interval: 1m
  values:
    hubble:
      metrics:
        enabled:
        - dns:query
        - drop
        - tcp
        - flow
        - icmp
        - http
      relay:
        enabled: true
      ui:
        enabled: true
        ingress:
          enabled: true
          className: traefik
          hosts:
          - hubble.home.frickel.earth
        replicas: 1
    ipam:
      mode: kubernetes
    ipv4:
      enabled: true
    ipv6:
      enabled: true
    k8sServiceHost: 10.134.0.100
    k8sServicePort: 6443
    kubeProxyReplacement: strict
    l7Proxy: false
    encryption:
      enabled: true
      type: wireguard
    operator:
      replicas: 1
    prometheus:
      enabled: true
