apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 5m
  timeout: 20m
  chart:
    spec:
      chart: longhorn
      version: '1.6.2'
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  values:
    persistence:
      defaultClassReplicaCount: 1
    ingress:
      enabled: true
      ingressClassName: traefik
      host: longhorn.home.frickel.earth
